name: Helm Chart Update CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
    - helm/src/**

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test
      working-directory: helm/src
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python check_helm_charts.py -c test/charts.yaml -o output.json
